/**
 * Centralized branding assets for CrabPal.
 *
 * All user-facing URLs, contact emails, and GitHub repo references live here.
 * When the `crabpal.app` domain is registered, flip the constants below to switch
 * the whole app over in one place.
 *
 * NOTE: package.json, shell install scripts, and electron-builder.yml cannot import
 * from this module — keep those in sync manually if any of these values change.
 */

export const CRABPAL_WORDMARK = ['CrabPal'] as const;
export const CRABPAL_WORDMARK_HTML = CRABPAL_WORDMARK.join('\n');

// ---------------------------------------------------------------------------
// GitHub repository (canonical distribution channel until a domain is purchased)
// ---------------------------------------------------------------------------

export const GITHUB_OWNER = 'boykioyb';
export const GITHUB_REPO = 'crab-pal';
export const GITHUB_DEFAULT_BRANCH = 'main';

export const GITHUB_REPO_URL = `https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}`;
export const GITHUB_README_URL = `${GITHUB_REPO_URL}#readme`;
export const GITHUB_SECURITY_ADVISORIES_URL = `${GITHUB_REPO_URL}/security/advisories/new`;
export const GITHUB_RELEASES_API_URL = `https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}/releases/latest`;
export const GITHUB_RELEASES_DOWNLOAD_URL = `${GITHUB_REPO_URL}/releases/latest/download`;
export const GITHUB_RAW_URL = `https://raw.githubusercontent.com/${GITHUB_OWNER}/${GITHUB_REPO}/${GITHUB_DEFAULT_BRANCH}`;

// ---------------------------------------------------------------------------
// Contact / attribution
// ---------------------------------------------------------------------------

export const SUPPORT_EMAIL = `${GITHUB_OWNER}@users.noreply.github.com`;
/** Used as the Co-Authored-By trailer in git commits generated by the agent. */
export const CO_AUTHOR_EMAIL = 'crabpal-agents@users.noreply.github.com';

// ---------------------------------------------------------------------------
// Public-facing branded URLs
// ---------------------------------------------------------------------------

/** Session viewer base URL — no hosted viewer yet, so point at the repo. */
export const VIEWER_URL = GITHUB_REPO_URL;
/** Documentation base URL — no hosted docs site yet, so point at the README. */
export const DOCS_URL = GITHUB_README_URL;
/**
 * Hosted docs MCP server. Empty by default because no endpoint is published yet;
 * set `DOCS_MCP_URL` env var to a reachable URL to re-enable the docs upstream proxy.
 */
export const DOCS_MCP_URL = '';
